locations = [-10.392627, 49.681847, 1.055039, 61.122019]
words = [
    "Boris",
    "Prime Minister",
    "Tories",
    "UK",
    "London",
    "England",
    "Manchester",
    "Sheffield",
    "York",
    "Southampton",
    "Wales",
    "Cardiff",
    "Swansea",
    "Banff",
    "Bristol",
    "Oxford",
    "Birmingham",
    "Scotland",
    "Glasgow",
    "Edinburgh",
    "Dundee",
    "Aberdeen",
    "Highlands" "Inverness",
    "Perth",
    "St Andrews",
    "Dumfries",
    "Ayr" "Ireland",
    "Dublin",
    "Cork",
    "Limerick",
    "Galway",
    "Belfast",
    " Derry",
    "Armagh" "BoJo",
    "Labour",
    "Liberal Democrats",
    "SNP",
    "Conservatives",
    "First Minister",
    "Surgeon",
    "Chancelor" "Boris Johnson",
    "BoJo",
    "Keith Stramer",
]

place = "London"
latitude = "51.450798"
longitude = "-0.137842"
radius = "10km"
geocode = f"{latitude},{longitude},{radius}"
